"""add cascade delete to query history

Revision ID: 25b3e40c76f1
Revises: a660b8aeed69
Create Date: 2025-04-20 19:36:23.580956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b3e40c76f1'
down_revision: Union[str, None] = 'a660b8aeed69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
