"""tenant model

Revision ID: 659e55eb1cc6
Revises: 25b3e40c76f1
Create Date: 2026-04-27 03:27:25.105669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '659e55eb1cc6'
down_revision: Union[str, None] = '25b3e40c76f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('owner_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'organization', 'user', ['owner_user_id'], ['id'])
    op.add_column('workspace', sa.Column('owner_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workspace', 'user', ['owner_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace', type_='foreignkey')
    op.drop_column('workspace', 'owner_user_id')
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_column('organization', 'owner_user_id')
    # ### end Alembic commands ###
